version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: parity-scale-codec
    versions:
    - 2.0.0
    - 2.0.1
    - 2.1.0
  - dependency-name: serde
    versions:
    - 1.0.123
    - 1.0.124
  - dependency-name: sp-std
    versions:
    - 2.0.1
    - 3.0.0
  - dependency-name: sp-runtime
    versions:
    - 2.0.1
  - dependency-name: frame-support
    versions:
    - 2.0.1
  - dependency-name: sp-core
    versions:
    - 2.0.1
  - dependency-name: sp-io
    versions:
    - 2.0.1
